# Generated by Django 5.1 on 2025-10-31 18:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=api.models.generate_random_user_id, primary_key=True, serialize=False),
        ),
    ]
