# Generated by Django 5.1 on 2025-04-14 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'user_note',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
