# Generated by Django 5.1 on 2025-11-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usernote',
            name='note_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
